//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 07:48:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0") package schemas.thing_description.v1_0;
